In [1]:
import pandas as pd
import numpy as np

In [2]:
list = [[12,43,"Python", 40, True],[23,43,43,54,66,65]]

In [3]:
data = pd.Series(list)
print(data)
print(type(data))

0    [12, 43, Python, 40, True]
1      [23, 43, 43, 54, 66, 65]
dtype: object
<class 'pandas.core.series.Series'>

In [4]:
data = pd.Series(list, index=['a','b'])
print(data)

a    [12, 43, Python, 40, True]
b      [23, 43, 43, 54, 66, 65]
dtype: object

In [5]:
dict_data = {'apple': 100, 'banana': 200, 'orange': 150}
s4 = pd.Series(dict_data)
print(s4)

apple     100
banana    200
orange    150
dtype: int64

In [6]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df1 = pd.DataFrame(data)
df1

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston

In [7]:
df1[['Name','Age']][0:2]

    Name  Age
0  Alice   25
1    Bob   30

In [8]:
coffee = pd.read_csv('coffee.csv')

In [9]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          12
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [10]:
excel_data = pd.read_excel('olympics-data.xlsx', sheet_name= 'bios')

In [11]:
excel_data.columns

Index(['athlete_id', 'name', 'born_date', 'born_city', 'born_region',
       'born_country', 'NOC', 'height_cm', 'weight_kg', 'died_date'],
      dtype='object')

In [12]:
excel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [13]:
excel_data.describe()

          athlete_id      height_cm      weight_kg
count  145500.000000  106651.000000  102070.000000
mean    73686.188955     176.333724      71.890996
std     42868.960158      10.380282      14.465540
min         1.000000     127.000000      25.000000
25%     36663.750000     170.000000      62.000000
50%     73302.500000     176.000000      70.000000
75%    110306.250000     183.000000      80.000000
max    149814.000000     226.000000     198.000000

In [14]:
excel_data[['name','born_date']][(excel_data['height_cm']>160.0) & (excel_data['born_date']=='1958-09-02')]

                        name   born_date
16414           Graham Seers  1958-09-02
28343        Beate Renschler  1958-09-02
38855       Stephanie Foster  1958-09-02
46016        Enrique Ledesma  1958-09-02
50491  Aleksandr Manachinsky  1958-09-02
50686           Jeanne Haney  1958-09-02

In [15]:
excel_data['athlete_id'].loc[:400]

0        1
1        2
2        3
3        4
4        5
      ...
396    397
397    398
398    399
399    400
400    401
Name: athlete_id, Length: 401, dtype: int64

In [16]:
excel_data.iloc[:300,0:3]

     athlete_id                   name   born_date
0             1  Jean-François Blanchy  1886-12-12
1             2         Arnaud Boetsch  1969-04-01
2             3           Jean Borotra  1898-08-13
3             4        Jacques Brugnon  1895-05-11
4             5           Albert Canet  1878-04-17
..          ...                    ...         ...
295         296             Carole Toy  1948-07-18
296         297            David Anear  1948-03-26
297         298      Christopher Blake  1953-06-13
298         299         Scott Dumbrell  1961-02-03
299         300      Simon Fairweather  1969-10-09

[300 rows x 3 columns]

In [17]:
excel_data.shape

(145500, 10)

count()

value_counts()

unique

isnull()

sum()

copy()

astype()

to_

concat

merge

groupby

sort_values()

drop

duplicated()

In [18]:
excel_data.count()

athlete_id      145500
name            145500
born_date       143693
born_city       110908
born_region     110908
born_country    110908
NOC             145499
height_cm       106651
weight_kg       102070
died_date        33940
dtype: int64

In [22]:
excel_data['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Bodrogkisfalud        1
Ternberg              1
Klaus                 1
Plaški                1
Dulwich Hill          1
Name: count, Length: 22368, dtype: int64

In [23]:
excel_data.isnull().sum()

athlete_id           0
name                 0
born_date         1807
born_city        34592
born_region      34592
born_country     34592
NOC                  1
height_cm        38849
weight_kg        43430
died_date       111560
dtype: int64

In [24]:
excel_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [25]:
excel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [30]:
excel_data['height_cm'] = excel_data['height_cm'].astype(object)

In [31]:
excel_data['height_cm'].dtype

dtype('O')

In [32]:
excel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  object
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(1), int64(1), object(8)
memory usage: 11.1+ MB

In [35]:
excel_data['died_date'] = pd.to_datetime(excel_data['died_date'])

In [36]:
excel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  object
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 11.1+ MB

In [37]:
excel_data['height_cm'] = pd.to_numeric(excel_data['height_cm'])

In [38]:
excel_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 11.1+ MB

In [39]:
x = excel_data.iloc[:300,:]
y = excel_data.iloc[300:460, :]

In [48]:
new_df = pd.concat((x,y),axis = 0)

In [49]:
new_df.shape

(460, 10)

In [50]:
c_codes = pd.read_excel('Country-Code.xlsx')

In [51]:
c_codes.head()

   Country Code    Country
0             1      India
1            14  Australia
2            30     Brazil
3            37     Canada
4            94  Indonesia

In [52]:
excel_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25